import { Area } from '../tipos/area.type';
import { ClasseNatureza } from '../tipos/classe-natureza.type';
import { AnexoInterface } from './anexo.interface';
import { AudienciaInterface } from './audiencia.interface';
import { MovimentacaoInterface } from './movimentacao.interface';
import { PartesInterface } from './partes.interface';
import { ProcessoRelacionadoInterface } from './processos-relacionados.interface';

export interface CnjInterface {
  regionalCnj: boolean | null;
  alternativeNumber: string;
  role: string;
  natureId: number;
  rod: string;
  natureClass: string;
  roleId: number;
  movements: MovimentacaoInterface[];
  distributionType: string;
  situation: string | null;
  jugde: string | null;
  area: Area;
  extraSubject: string;
  injunction: boolean | null;
  audiences: AudienciaInterface[];
  originalRod: string;
  free: boolean | null;
  value: number | null;
  attachments: AnexoInterface[];
  updateDate: string;
  systemFont: string;
  forum: string;
  situationId: number | null;
  verdictDate: string | null;
  instance: number;
  relatedProcesses: ProcessoRelacionadoInterface[];
  number: string;
  customs: unknown[];
  flag: boolean;
  judicialDistrictCnj: string;
  judicialDistrict: string;
  tribunalId: number;
  natureClassDigesto: ClasseNatureza;
  forumCnj: string;
  tribunal: string;
  areaId: number;
  processId: number;
  distributionDate: string;
  hasSecretJustice: boolean;
  isFiled: boolean;
  classes: string[];
  access: string[];
  uf: string;
  createDate: string;
  parts: PartesInterface[];
  polo: boolean;
}
